services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: business_tracker_app
    depends_on:
      - postgres_db
      - mssql_db
    environment:
      - ConnectionStrings__Postgres=Host=postgres_db;Port=5432;Database=business_tracker;Username=postgres;Password=postgres
      - ConnectionStrings__Mssql=Server=mssql_db,1433;Database=business_tracker;User Id=sa;Password=qwerty-05;TrustServerCertificate=True;

  postgres_db:
    image: postgres:latest
    container_name: business_tracker_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: business_tracker
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql

  mssql_db:
    image: mcr.microsoft.com/azure-sql-edge:latest # for MacOS with M chip
    container_name: business_tracker_mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "qwerty-05"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_data:/var/opt/mssql